### PR TITLE
Add extra_params for custom authorizeUrl generating

### PR DESCRIPTION
**Pull request by zharinov**
Hello, Adam! Thank you for this package.
My request is possible solution of #34

### CODE REVIEW

**Comment by mirago** [comment]
:+1:

**Comment by adamwathan** [comment]
Thanks for the PR! Can anyone confirm this would be useful for other providers aside from Google? That's my main concern, don't want to introduce something as a general feature that's only useful for one provider.

The main goal of this library is to allow authentication with third party providers in apps that aren't otherwise making use of that provider's API. So cases where you want to login with Google, but after that you never care about talking to Google again. Past that, it isn't useful to generalize things and it's typically better to just use an SDK for a specific provider's API.

**Comment by zharinov** [comment]
Agree, better decision is extending only Google provider, so i'll fix this PR sometime later

**Comment by zharinov** [comment]
UPD. i need more sleep, sorry :) now i got the idea, it's about L from SOLID abbreviation

**Pull request closed without merging**
