### PR TITLE
Changed InstallCommand file to properly publish migration file.

### PR DESCRIPTION
**Pull request by pavankumarkatakam**
Problem : As the create_oauth_identities_table as original file and when it is published both original and published file are colliding an results to error. So make the file as stub and then use laravel for migrating it.

### CODE REVIEW

**Comment by adamwathan** [comment]
Thanks for the PR!

I'm not sure I understand the problem, I've never seen an error or any collisions myself. Here's a video of installing the package in a fresh L5 app with no issues: https://vimeo.com/120085196

What process were you using for installing the package assets that was causing an issue?

I do like the idea of using the MigrationCreator with a stub for a variety of reasons and didn't know about it until this PR (thanks for that!) but unfortunately it's not quite flexible enough to do what we would need. Using it just to get a path, and then overriding the file it creates is a little hacky :/

**Comment by pavankumarkatakam** [comment]
Actually problem is you have class in package called "CreateOauthIdentitiesTable"  and then we use Install command the migrations in our main project is created with the name "CreateOauthIdentitiesTable" now the when running the php artisan migrate:reset it looking for the "CreateOauthIdentitiesTable" but it is not loading because there are two classes having the same name ... so in your packge if we make it as stub then laravel treat this stub as php and we have only one "CreateOauthIdentitiesTable" class.

   I have already watched the video there you not mention the commands migrate:reset or migrate:refresh. 

  To correctly understand my problem please make an example with your package do migrate:reset or migrate:refresh

**Comment by adamwathan** [comment]
Ahh ok I see what you're saying! It's not an issue of the two classes existing though, the one in the package is not auto-loaded.

I recreated the scenario you're talking about and resolved the error by doing a `composer dump-autoload`. The problem was that my migration wasn't being added to the autoloader on install :/ I've pushed a fix for that now though :+1: 

If you still have issues please let me know, unfortunately gonna close this for now. I still do like the idea of using the MigrationCreator but it's not flexible enough to work properly with packages as it stands :/

**Comment by pavankumarkatakam** [comment]
Yeah it fixed now and there is no errors when doing migrate:refresh. But please explain me y it not flexible enough to work properly with packages as it stands.

**Comment by pavankumarkatakam** [comment]
> Using it just to get a path, and then overriding the file it creates is a little hacky :/
This is trick is followed by Laravel framework.

**Comment by pavankumarkatakam** [comment]
And one more thing is still my editor PhpStorm showing the both classes as warning that "There is other declaration of class 'CreateOauthIdentitiesTable' in the same project"

**Comment by adamwathan** [comment]
My main complaint is just the detail I mentioned before, where we used the MigrationCreator to create a migration, then store the filename and completely override the file. If we were just using it to generate the filename explicitly without the side effect of creating a file I think it would bother me less :/

Do you have a reference for where the framework is using it the same way? It seems really bizarre to me to go through all the trouble of creating a file just to get a filename, then overriding the file.

I'll give the stub migration a different extension so PHPStorm doesn't complain :+1:

**Comment by pavankumarkatakam** [comment]
>Do you have a reference for where the framework is using it the same way? It seems really bizarre to me to go through all the trouble of creating a file just to get a filename, then overriding the file.


This is the [CreateCacheTablestub](https://github.com/laravel/framework/blob/master/src/Illuminate/Cache/Console/stubs/cache.stub) in laravel

**Comment by pavankumarkatakam** [comment]
> I'll give the stub migration a different extension so PHPStorm doesn't complain :+1:

Yes, i renamed the extension to .stub, that is the Pull request. I think u r using .php only in sorce files.

**Comment by pavankumarkatakam** [comment]
Ok, i understand the use of MigrationPublisher.php file now. i think just renaming the migration file extension is sufficient.

**Comment by adamwathan** [comment]
Seeing that Taylor used the same approach you did within the framework makes me feel less bad about it and would let me delete that entire MigrationPublisher class so I'm leaning more towards just pulling this in :)

Couple changes before merging:

1. I would still like it if we kept the migration stub where it originally was instead of mixed into the PSR-4 folders, so just in `migrations/create_oauth_identities_table.stub`.

2. Can you update the PR to include deleting the MigrationPublisher entirely? :)

**Comment by pavankumarkatakam** [comment]
is .gitkeep file in migrations folder is necessary. if you want i will add that also.

**Comment by adamwathan** [comment]
Nah probably fine to lose the .gitkeep. Thanks for this, going to get it merged in later this afternoon when I have a chance to fix the conflict I introduced when I fixed the autoloading issue :)

**Comment by pavankumarkatakam** [comment]
:-)

**Comment by pavankumarkatakam** [comment]
Actually i have started to create a Package on Oatuh but i don't have much time. And i propose you to include other Oauth providers also.

**Comment by adamwathan** [comment]
Finally getting around to merging this but realizing that running install multiple times creates multiple migrations which the original implementation didn't do, so just need to resolve that.

Have the branch setup here: https://github.com/adamwathan/eloquent-oauth/tree/pavankumarkatakam-laravel-5

Gonna try get it sorted out tonight.

**Comment by adamwathan** [comment]
Merged in here: https://github.com/adamwathan/eloquent-oauth/commit/ffa6bb756373f3135a88a03ca96b94173cc0787c

Thanks again for the PR!

**Pull request closed without merging**
