### PR TITLE
Readme: Add advanced section to explain accessing $details->raw()[]

### PR DESCRIPTION
**Pull request by drbyte**
Inspired by discussion in #44

### CODE REVIEW

**Comment by adamwathan** [comment]
Amazing! Thanks Chris!

**Comment by Hjsurk** [comment]
Awesome! Well done! :+1:

**Comment by dusterio** [comment]
This needs some some revamp I think? Most of the fields are not longed returned by Facebook API automatically (eg. gender), unless explicitly asked for. And SocialNorm has a list of fields hard coded, I don't see any non-intrusive way to really access, let's say, user's gender

**Comment by adamwathan** [comment]
Hey @dusterio, as the readme mentions this package is abandoned and no longer maintained. Feel free to fork if you’d like to make updates for your own use.

**Pull request merged**
